/*
 * This source file was generated by the Gradle 'init' task
 */
package no1;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.print("Enter number for calculate: ");
        int number = sc.nextInt();
        if (number < 0 || number > 99) {
            System.out.println("Calculation " + number + " Factorial");
            sc.close();
        }

        int factorial = 1;

        for (int i = 1; i <= number; i++) {
            System.out.println(i + " ! = " + factorial);
            factorial = factorial * i;
        }

        System.out.println("\nCalculation Fibonanci number: " + number);
        int a = 0, Fibonacci = 1;
        if (number >= 0) {
            System.out.println("f0 = " + a);
        }
        if (number >= 1) {
            System.out.println("f1 = " + Fibonacci);
        }
        for (int i = 2; i <= number; i++) {
            int c = a + Fibonacci;
            a = Fibonacci;
            Fibonacci = c;
            System.out.println("f" + i + " = " + Fibonacci);
        }
        int total = factorial - Fibonacci;
        
        System.out.println(factorial + " Factorial minus Fibonanci number " + Fibonacci + " is " + total);
    }

    
}
