/*
 * This source file was generated by the Gradle 'init' task
 */
package no2;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static int mymax(int a, int b, int c) {
        int max = a;
        if (b > max) {
            max = b;
        }
        if (c > max) {
            max = c;
        }
        return max;
    }

    public static int mymin(int a, int b, int c) {
        int min = a;
        if (b < min) {
            min = b;
        }
        if (c < min) {
            min = c;
        }
        return min;
    }

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.print("Enter first number: ");
        int a = sc.nextInt();
        System.out.print("Enter second number: ");
        int b = sc.nextInt();
        System.out.print("Enter last number: ");
        int c = sc.nextInt();
        int max = mymax(a, b, c);
        int min = mymin(a, b, c);
        int total = max + min;
        System.out.println("Max value: " + max + "\nMin value: " + min);
        System.out.print("Total Max plus Min is " + total);
        sc.close();
    }
}
